spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wnt_db
    username: joonseo
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace